FROM python:3.11-slim
WORKDIR /app
RUN pip install --no-cache-dir -r fastapi uvicorn[standard] psycopg2-binary sqlalchemy python-dotenv
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]